import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";

export const users = [
  {
    _id: uuid(),
    firstName: "Sameep",
    lastName: "Sharma",
    displayImage: "https://res.cloudinary.com/sameep1/image/upload/v1654631646/project_socialMedia/profilePP_vtnjlt.png",
    username: "sameep",
    email: "sameep@gmail.com",
    password: "p123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Robert",
    lastName: "wang",
    displayImage: "https://res.cloudinary.com/sameep1/image/upload/v1654805501/project_socialMedia/hacker_e1vg0u.png",
    username: "mrrobotwang",
    email: "robert@gmail.com",
    password: "p123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Phunsuk",
    lastName: "Wangdoo",
    displayImage: "https://res.cloudinary.com/sameep1/image/upload/v1654805501/project_socialMedia/programmer_qht6f1.png",
    username: "wangdoer",
    email: "phunsuk@gmail.com",
    password: "p123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Elongated",
    lastName: "Musket",
    displayImage: "https://res.cloudinary.com/sameep1/image/upload/v1654805501/project_socialMedia/man_1_ezefji.png",
    username: "tothemoon",
    email: "musk@gmail.com",
    password: "p123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Jhon",
    lastName: "Doe",
    displayImage: "https://res.cloudinary.com/sameep1/image/upload/v1654805501/project_socialMedia/man_tejzmh.png",
    username: "jhondoe",
    email: "jhon@gmail.com",
    password: "p123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Jane",
    lastName: "Doe",
    displayImage: "https://res.cloudinary.com/sameep1/image/upload/v1654805501/project_socialMedia/woman1Avatar_c8wems.png",
    username: "janedoe",
    email: "jane@gmail.com",
    password: "p123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Mary",
    lastName: "jane",
    displayImage: "https://res.cloudinary.com/sameep1/image/upload/v1654805501/project_socialMedia/user_heo4gj.png",
    username: "watson",
    email: "mary@gmail.com",
    password: "p123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
